### ISSUE TITLE
Small UX improvement. 

### ISSUE THREAD

**Issue by ksharlandjiev** [aws-samples/serverless-coffee-workshop#6]
1. I had minor issues while configuring OrderProcessorWorkflow: 

- I had to manually create a IAM Policy to allow the Step Function to execute ListExecutions.
- I had to manually create a IAM Policy to allow the Step Function to perform PutEvents on the Serverless event bus. 
- I had to manually create a IAM policy to allow SF to execute dynamodb:UpdateItem on serverlesspresso-counting-table DDB table.
- If the store is set to be closed, and you execute the OrderProcessor manually without input payload, the "Emit - Shop not ready" step is failing. 

2. I ran into CORS problems - while on the configuration page for the front end, I evidently copied one of the API endpoints with extra white spaces at the end, like this: "https://******.execute-api.us-east-1.amazonaws.com/Prod/     ", resulting in the app not able to generate QR codes - may be consider using trim() before saving the configuration in the local browser storage. 

Great work, I absolutely enjoyed the experience.

**Comment by bls20AWS** [comment]
Thanks for submitting and recording the issues. The issues relating to IAM Policy, sounds like it's because you selected the wrong IAM role when applying it to your workflow. This is a common and easy mistake, i think we should make the name of the role more unique so it's easier to spot. 

The second is a great Idea. Would you like to contribute with  a PR?  I'd be happy to merge?

Really Glad you Enjoyed the workshop.

Thanks again for taking the time to leave feedback!
